export const GENERATE_QUESTIONS = 'GENERATE_QUESTIONS';
export const SETUP_DATASET = 'SETUP_DATASET';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const RESET_ANSWERS = 'RESET_ANSWERS';
