export const SET_RANDOM_PHRASE = 'SET_RANDOM_PHRASE';
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE';

export const SEARCH_VIDEO = 'SEARCH_VIDEO';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_ERROR = 'SEARCH_VIDEO_ERROR';

export const MOVE_TO_NEXT_VIDEO = 'MOVE_TO_NEXT_VIDEO';
